# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.4
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: nextmachenic@gmail.com
author_name: Harsh Parihar
cloud_provider: netlify
contract_name: credchain_contract
preset_name: production
project_name: CredChain

